### ISSUE TITLE
Leading wildcards don't work

### ISSUE THREAD

**Issue by floatingLomas** [DamonOehlman/wildcard#8] opened 2015-05-22 22:45 UTC
`*.foo.com` does not match `foo.com`; however, I can get it to do so by reversing both strings.

Is this expected behaviour?

**Comment by DamonOehlman** [comment] 2015-05-24 23:52
I think this should be made to work, so I'll try and get time to implement it sometime soon.  PR's are also gratefully accepted :)

**Comment by bradennapier** [comment] 2017-01-16 02:10
This is pretty old - but just wanted to note that `*.foo.com` would match `.foo.com` -- perhaps you wanted `*foo.com` ?

**Comment by revelt** [comment] 2017-04-23 21:05
Regarding @floatingLomas question, your example is wrong because the leading full stop, the first character, is missing in `foo.com`. However, your accusation is legit! Here's a better, correct example:

    var wildcard = require("wildcard")
    var res = wildcard('*foo', 'foo')
    console.log('res = ' + res)
    // -> "res = false"

The `res` should be `true`. This drives me mad, there's another library, [wildstring](https://www.npmjs.com/package/wildstring) which has this very same issue and was driving me mad so much that I came looking for alternative, but this library misbehaves too!

According to Wikipedia:

> "In software, a wildcard character is a single character, such as an asterisk (*), used to represent a number of characters or an **empty string**" (emphasis mine, RR).
— https://en.wikipedia.org/wiki/Wildcard_character

What means, this library is incorrect _conceptually_, treating wildcard character as _at least one character_ instead of _zero or more characters_.

You see?

Try running this on [RunKit](https://runkit.com/58fd11151dc1c60013c79f85/58fd132d15bef7001293f41a).

We need a new wildcard library with a correct algorithm (or this one fixed).

**Comment by bradennapier** [comment] 2017-04-23 21:09
https://github.com/Dash-OS/redux-saga-process/blob/master/src/lib/wildcard.js

I largely re-created wildcard in the redux-saga-process code provided @revelt might find something useful

**Comment by revelt** [comment] 2017-04-23 21:12
@bradennapier dude you should publish it as a standalone lib on npm! Will check it out right now. I prefer standalone libraries from npm because they're self-contained, with unit tests and API documentation. I can help you to publish it and add you to maintainers if you want. What do you think?

**Comment by bradennapier** [comment] 2017-04-23 21:15
Considered it, not 100% sure what I even did there honestly - redux-saga-process is a npm library but obviously the wildcard is not.  It's meant to take an object with wildcards and filter it for redux patterns.

```javascript
static actionRoutes = {
    '*Probe': 'probe'
};
```

**Comment by bradennapier** [comment] 2017-04-23 21:19
One of the main issues I had is most of them were requiring node whereas I needed it to work in the browser.

**Comment by bradennapier** [comment] 2017-04-23 21:22
https://github.com/Dash-OS/redux-saga-process/blob/master/src/lib/reducerGenerators.js#L30-L41

You can see it being used there

**Comment by revelt** [comment] 2017-04-23 21:25
Thank you. That's quite an advanced level of JS by the way. I'm thinking how I'd write this from scratch, with bunch `for` loops, `if`'s and inner state flag variables.

**Comment by revelt** [comment] 2017-04-23 21:40
## Notes for posterity no.1.
I switched to another library to match strings with wildcards, [matcher](https://www.npmjs.com/package/matcher). It does the job well and supports the leading wildcards out of the box. 

## Notes for posterity no.2.
Another string wildcard library, [wildstring](https://www.npmjs.com/package/wildstring) also has this very same [issue](https://github.com/deltreey/wildstring/issues/2) with leading wildcards, so don't waste your time with it either. Stick with [matcher](https://www.npmjs.com/package/matcher).

**Comment by bradennapier** [comment] 2017-04-23 22:06
@revelt heh yeah I like to try to write things as efficient as possible.  It's EXTREMELY performant when you run it.  Would be interesting to test it against matcher.  Looks like a simple enough library and a good choice overall though.

**Comment by DamonOehlman** [comment] 2017-04-26 06:49
Apologies for letting this one slip folks.  I'll add a note that people should definitely consider using `matcher` if they have come across this library.  Additionally, add a test case that demonstrates this breaking case and fix it as I agree with @revelt it is definitely a violation of the expected behaviour of `*` in all expected instances.

**Comment by DamonOehlman** [comment] 2019-01-07 06:38
Fixed by #11 - also added a note to the README directing people to `matcher` as it's *definitely* better maintained...

**Closed by DamonOehlman** 2019-01-07 06:38 UTC
